# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-SymbolicX-NoSimplification
version:      0.01
version_from: lib/Math/SymbolicX/NoSimplification.pm
installdirs:  site
requires:
    Test::More:                    0
    Math::Symbolic:                0.128

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
