--- #YAML:1.0
name:                Math-SymbolicX-NoSimplification
version:             1.01
abstract:            Turn off Math::Symbolic simplification
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Math::Symbolic:                0.128
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steffen Mueller <symbolic-module at steffen-mueller dot net>
